version: '3.7'
services:
  postgres:
    container_name: ccn_postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - nx-microservice-network

  redis:
    container_name: ccn_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
    driver: local

networks:
  nx-microservice-network:
    driver: bridge
