version: '3.7'
services:
  postgres:
    container_name: ccn_prod_postgres
    image: postgres:${DB_VERSION}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - ccn-prod-network

  redis:
    container_name: ccn_prod_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - ccn-prod-network

  prometheus:
    container_name: ccn_prod_prometheus
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - ccn-prod-network

  grafana:
    container_name: ccn_prod_grafana
    image: grafana/grafana:latest
    volumes:
      - '$PWD/monitoring/grafana:/var/lib/grafana'
      - metrics-ui-data:/var/lib/grafana
      - ./docker/grafana:/etc/grafana/provisioning
    links:
      - prometheus:prometheus
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - '3000:3000'
    networks:
      - ccn-prod-network

  gateway:
    container_name: ccn_prod_gateway
    image: ccn-gateway
    depends_on:
      - 'redis'
      - 'postgres'
    environment:
      - DB_VERSION=13-alpine
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_DATABASE=ccn
      - DB_PORT=5432
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - SEEDING_ENABLED=true
    ports:
      - '3333:3333'
    networks:
      - ccn-prod-network

  incidence-service:
    container_name: ccn_prod_incidence_service
    image: ccn-incidence-service
    depends_on:
      - 'redis'
      - 'postgres'
    environment:
      - DB_VERSION=13-alpine
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_DATABASE=ccn
      - DB_PORT=5432
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - SEEDING_ENABLED=true
    ports:
      - '8082:3333'
    networks:
      - ccn-prod-network

  qr-code-service:
    container_name: ccn_prod_qr_code_service
    image: ccn-qr-code-service
    depends_on:
      - 'redis'
      - 'postgres'
    environment:
      - DB_VERSION=13-alpine
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_DATABASE=ccn
      - DB_PORT=5432
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - SEEDING_ENABLED=true
    ports:
      - '8083:3333'
    networks:
      - ccn-prod-network

  sessionservice:
    container_name: ccn_prod_session_service
    image: ccn-session-service
    depends_on:
      - 'redis'
      - 'postgres'
    environment:
      - DB_VERSION=13-alpine
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_DATABASE=ccn
      - DB_PORT=5432
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - SEEDING_ENABLED=true
    ports:
      - '8084:3333'
    networks:
      - ccn-prod-network

  room-service:
    container_name: ccn_prod_room_service
    image: ccn-room-service
    depends_on:
      - 'redis'
      - 'postgres'
    environment:
      - DB_VERSION=13-alpine
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_DATABASE=ccn
      - DB_PORT=5432
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - SEEDING_ENABLED=true
    ports:
      - '8085:3333'
    networks:
      - ccn-prod-network

volumes:
  postgres:
  redis:
    driver: local
  metrics-ui-data:

networks:
  ccn-prod-network:
