apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    jsonData:
      timeInterval: 1s
      prometheusVersion: '2.40.0'
      prometheusType: Prometheus
    version: 1
    editable: true
