global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'gateway'
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - 'gateway:3333'
  - job_name: 'traefik'
    static_configs:
      - targets:
          - 'traefik:8080'
