global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: /api/metrics
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - 'gateway:3333'
  - job_name: 'traefik'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - 'traefik:8080'
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'grafana'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - 'grafana:3000'
