{
 "title": "TEST1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traefik Entrypoint Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "traefik_entrypoint_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "stat",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "GATEWAY_NestJS_Health", "legendFormat": "Gateway" },
    { "expr": "GATEWAY_Database_Health", "legendFormat": "Database" },
    { "expr": "GATEWAY_Redis_Health", "legendFormat": "Redis" },
    {
     "expr": "GATEWAY_Sessions_Service_Health",
     "legendFormat": "Sessions Service"
    },
    { "expr": "GATEWAY_Rooms_Service_Health", "legendFormat": "Rooms Service" },
    {
     "expr": "GATEWAY_Incidence_Service_Health",
     "legendFormat": "Incidence Service"
    },
    { "expr": "GATEWAY_QrCode_Service_Health", "legendFormat": "QR Code Service" }
   ]
  },
  {
   "title": "Gateway NodeJS Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "GATEWAY_nodejs_active_resources_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway NodeJS Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "GATEWAY_nodejs_active_requests_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}