name: ci
on:
  pull_request:
    branches:
      - master
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm i
      - run: npm run lint:all

  # prettier:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   if: ${{ !contains(github.event.head_commit.message, 'Prettified Code!') }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         # Make sure the actual branch is checked out when running on pull requests
  #         ref: ${{ github.head_ref }}
  #         # This is important to fetch the changes to the previous commit
  #         fetch-depth: 0

  #     - name: Prettify code
  #       uses: creyD/prettier_action@v4.2
  #       with:
  #         # This part is also where you can pass other options, for example:
  #         prettier_options: --write .
  #         only_changed: true
